# General Overview

<script>
$("#coverpic").hide();
</script>

The weekly labs are structured to give students experience with conducting experiments, analyzing data, thinking critically about theory and data, and communicating their results and analysis in writing and oral presentation.

Lab instructors facilitate this process by guiding students through the demands of each of the labs. Lab instructors are there to help you, so ask them questions when you need answers!

## Lab structure: Major and mini projects, and presentations

The entire semester is divided into three major projects, and 3 mini projects. They are ordered consecutively to build upon skills. For example, the first projects focus on data analysis skills involving t-tests, then one-way ANOVAs, and finally 2x2 Factorial designs. Throughout each of the labs you will learn how to create experiments and conducts analyses on the data. Then you will employ these skills in the last half of the semester when you form groups and conduct, analyze, report and present an experiment of your own design.

## Major projects

Each major project involves students completing an experiment as a class (using themselves as subjects to collect data). Students will learn about the conceptual issues behind the experiment, collect data on themselves, and analyze the class data using appropriate statistics. Each student will then be responsible for writing a short (5+ page) APA style report about the project.

The first two major projects involve predefined experiments that the class completes. These two projects are roughly finished mid-semester, and are intended to train students in the skills needed to complete the final project. The last major project is the final project, where students form groups and complete an experiment based on their own design.

Each lab instructor is responsible for grading each of their students papers. Individual lab instuctors will explain to their sections how their grading scheme will work.

## Mini projects

In the first half of the semester, each of the weeks that does not introduce a new major project are reserved for mini-projects. These projects are intended to be completed within one lab session. Each of the mini-projects involve 1) reading and understanding a primary source, and 2) attempting to replicate the result in the paper. These are graded on a pass/fail basis, where a pass is given to students who show up and participate in the lab (regardless of whether their experiment turns out.)

## Presentations

The final project involves two presentations. An individual presentation, and a group presentation. Prior to forming groups for the final project, each student will give a short (2-3) minute pitch for their project idea. Then, students will form groups (choose one of the members project ideas, or generate a new one) and begin working on their final project. The last lab is reserved for the group presentations where each group gives a 10 minute research presentation.

## Grading

Each lab instructor will grade the work of the students in their sections. See the course syllabus for information on how each of the lab components weigh into the final grade for the course.

## Lab Resources

There are many resources to help you complete the lab assignments. These are included in this lab manual, as well as online.

## Website

As much as possible all of the information for this course will be posted on the course website:

<http://crumplab.github.io/courses/experimental/>

## Lab rooms

There should be one computer per student in each of the lab rooms. These computers should have SPSS, Excel, Office, R, Superlab, LIVECODE, and Psychopy installed on them.

## Lab manual

This lab manual contains instructions for each the lab assignments, as well as helpful tutorials for learning skills to analyze and report data.

## Lab Schedule

### Lab 1: Overview

1.  Meet and greet your instructor and fellow classmates, and learn about what is in store for the labs this semester

    a\. You will write three APA style research reports. Papers 1 and 2 will be on predefined projects, and Paper 3 will be based on a final project where students form groups to complete an experiment of their own design

    b\. The final project will involve two presentations, an individual presentation and a group presentation.

    c\. The first half of the semester involves completing Papers 1 and 2, and a few mini-projects that occur between papers 1 and 2. These will build the skills necessary to complete the final project which will take up most of the second half of the semester

2.  Students are expected to show up and be on time for labs

3.  Ask questions

4.  Go over QALMRI method using provided QALMRI materials

5.  Discuss/Review the components of writing an APA paper

### Lab 2: Paper project 1

Students replicate the results of @song_if_2008 (2008)@song_if_2008.

1.  Administer the experiment using the provided materials

    a\. Students will receive a piece of paper with instructions. They will read the description of an exercise routine, and then answer the questions about what they read.

2.  Reading and understanding the primary source

    a\. Students will be given the Song & Schwarz (2008) paper, and the to-be-filled in QALMRI worksheet. They will be given 15-20 minutes to read the paper, and in small groups attempt to fill out the QALMRI worksheet for the paper

    b\. Group discussion of the paper and the QALMRI

3.  Collect and analyze the data

4.  Discuss the paper assignment

### Lab 3: Paper project 1 continued

1.  More time to work on the first paper. Use your lab instructor as a resource and ask questions if you need more info.

    E.g., Review APA style, review the structure and content of the paper, review the results, edit each others work, etc.

2.  Due dates are set by the lab instructor

### Lab 4: MiniProject 1 Nairne, Pandeirada, & Thompson (2008)

Students replicate the results of @nairne_adaptive_2008 (2008)@nairne_adaptive_2008.

1.  Students read paper and write QALMRI (15-20)

2.  Group discussion about paper (15-20)

3.  Students attempt to replicate the major findings in the paper

    a\. Break into four-five groups, each group assigned an encoding condition (Survival, Pleasantness, Imagery, Self-reference, Intentional learning)

    b\. Each group picks their own 30 words. Can follow same procedure as in paper by choosing 30 words from Overschelde, Rawson, & Dunlosky (2004) @van_overschelde_category_2004.

    c\. Groups try to run at least 10 participants in their condition, recording proportion of correctly recalled words

    d\. Groups enter their collected data into the master spreadsheet, which is given back to groups upon data completion

4.  Discussion of how to analyze the data

5.  Group attempt to analyze the data using t-tests and one-way ANOVA to determine if the survival framing produced better recall than the other conditions.

### Lab 5: Mini Project 2 Stoet et al. (2013)

Students replicate the results of Stoet et al. (2008) @stoet_are_2013.

1.  Students read paper and write QALMRI (15-20)

2.  Group discussion about paper (15-20)

3.  Students download the task-switching program available from the website and individually complete the task. Individual students then enter their data in the master spreadsheet

4.  Discussion of how to analyze the data. Major analysis goals are:

    a\. Was there a mixing cost? Compare pure lists to mixed lists

    b\. Was there a switching cost? Compare switch vs. repeat trials in pure lists

    c\. Was there a gender effect?

5.  Students break into groups to analyze the data.

### Lab 6: Mini Project 4 Raz et al. (2006)

Students replicate the results of Raz et al. (2006) @raz_suggestion_2006

1.  Students read paper and write QALMRI (15-20)

2.  Group discussion about paper (15-20)

3.  Students instructed their task is create their own Stroop design and employ a manipulation that increases or decreases the size of the Stroop effect

4.  Students break into groups and conduct a Stroop experiment, measuring the size of the Stroop effect in a “normal” condition, and in their manipulated condition.

5.  Groups analyze conduct a 2x2 ANOVA to see if their interaction was significant

### Lab 7 : Paper Project 2 Yin (1969)

Students replicate the results of Yin (1969) @yin_looking_1969

1.  Students read paper and write QALMRI (15-20)

2.  Group discussion about paper (15-20)

3.  Students complete computerized task and report their data in the master spreadsheet. Data is given back to students for analysis

4.  Discussion about writing the 2nd paper

### Lab 8: Paper project 2 continued

1.  Extra-time for completing second paper, again use your lab instructor as a resource, they are there to help.

### Lab 9: Brainstorming for Final project

1.  Learn about details of the final project

2.  Learn about details of the individual presentation (next lab)

3.  Brainstorming session allowing students to think about possible projects that they would propose for their individual project

### Lab 10: Individual Presentations

1.  Students give their individual (2-3 minute) presentations

2.  Students are divided into groups for their final project

3.  Each group decides on the experiment for their final project. This could be from one of the individual project ideas, or a new idea. Groups need permission from the lab instructor for their final project before data collection begins

### Lab 11-13: Group work on Final Project

1.  Help groups finalize their final project aims

2.  Groups collect data

3.  Discuss requirements for final presentation and paper

### Lab 14: Final group presentations
