<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Research Methods: Lab Manual</title>
  <meta name="description" content="A lab manual for Psyc 3450">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Research Methods: Lab Manual" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A lab manual for Psyc 3450" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Research Methods: Lab Manual" />
  
  <meta name="twitter:description" content="A lab manual for Psyc 3450" />
  

<meta name="author" content="Matthew J. C. Crump">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="miniproject-one-memory.html">
<link rel="next" href="miniproject-three-stroop.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script type="text/javascript">
mattcrump=1;
</script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="tufte.css" type="text/css" />
<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Research Methods Lab Manual</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#important-notes"><i class="fa fa-check"></i><b>0.1</b> Important notes</a><ul>
<li class="chapter" data-level="0.1.1" data-path="index.html"><a href="index.html#attributions"><i class="fa fa-check"></i><b>0.1.1</b> Attributions</a></li>
<li class="chapter" data-level="0.1.2" data-path="index.html"><a href="index.html#cc-by-sa-4.0-license"><i class="fa fa-check"></i><b>0.1.2</b> CC BY-SA 4.0 license</a></li>
<li class="chapter" data-level="0.1.3" data-path="index.html"><a href="index.html#copying-the-lab-manual"><i class="fa fa-check"></i><b>0.1.3</b> Copying the lab manual</a></li>
<li class="chapter" data-level="0.1.4" data-path="index.html"><a href="index.html#acknowledgments"><i class="fa fa-check"></i><b>0.1.4</b> Acknowledgments</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="general-overview.html"><a href="general-overview.html"><i class="fa fa-check"></i><b>1</b> General Overview</a><ul>
<li class="chapter" data-level="1.1" data-path="general-overview.html"><a href="general-overview.html#lab-structure-major-and-mini-projects-and-presentations"><i class="fa fa-check"></i><b>1.1</b> Lab structure: Major and mini projects, and presentations</a></li>
<li class="chapter" data-level="1.2" data-path="general-overview.html"><a href="general-overview.html#major-projects"><i class="fa fa-check"></i><b>1.2</b> Major projects</a></li>
<li class="chapter" data-level="1.3" data-path="general-overview.html"><a href="general-overview.html#mini-projects"><i class="fa fa-check"></i><b>1.3</b> Mini projects</a></li>
<li class="chapter" data-level="1.4" data-path="general-overview.html"><a href="general-overview.html#presentations"><i class="fa fa-check"></i><b>1.4</b> Presentations</a></li>
<li class="chapter" data-level="1.5" data-path="general-overview.html"><a href="general-overview.html#grading"><i class="fa fa-check"></i><b>1.5</b> Grading</a></li>
<li class="chapter" data-level="1.6" data-path="general-overview.html"><a href="general-overview.html#lab-resources"><i class="fa fa-check"></i><b>1.6</b> Lab Resources</a></li>
<li class="chapter" data-level="1.7" data-path="general-overview.html"><a href="general-overview.html#website"><i class="fa fa-check"></i><b>1.7</b> Website</a></li>
<li class="chapter" data-level="1.8" data-path="general-overview.html"><a href="general-overview.html#lab-rooms"><i class="fa fa-check"></i><b>1.8</b> Lab rooms</a></li>
<li class="chapter" data-level="1.9" data-path="general-overview.html"><a href="general-overview.html#lab-manual"><i class="fa fa-check"></i><b>1.9</b> Lab manual</a></li>
<li class="chapter" data-level="1.10" data-path="general-overview.html"><a href="general-overview.html#lab-schedule"><i class="fa fa-check"></i><b>1.10</b> Lab Schedule</a><ul>
<li class="chapter" data-level="1.10.1" data-path="general-overview.html"><a href="general-overview.html#lab-1-overview"><i class="fa fa-check"></i><b>1.10.1</b> Lab 1: Overview</a></li>
<li class="chapter" data-level="1.10.2" data-path="general-overview.html"><a href="general-overview.html#lab-2-paper-project-1"><i class="fa fa-check"></i><b>1.10.2</b> Lab 2: Paper project 1</a></li>
<li class="chapter" data-level="1.10.3" data-path="general-overview.html"><a href="general-overview.html#lab-3-paper-project-1-continued"><i class="fa fa-check"></i><b>1.10.3</b> Lab 3: Paper project 1 continued</a></li>
<li class="chapter" data-level="1.10.4" data-path="general-overview.html"><a href="general-overview.html#lab-4-miniproject-1-nairne-pandeirada-thompson-2008"><i class="fa fa-check"></i><b>1.10.4</b> Lab 4: MiniProject 1 Nairne, Pandeirada, &amp; Thompson (2008)</a></li>
<li class="chapter" data-level="1.10.5" data-path="general-overview.html"><a href="general-overview.html#lab-5-mini-project-2-stoet-et-al.-2013"><i class="fa fa-check"></i><b>1.10.5</b> Lab 5: Mini Project 2 Stoet et al. (2013)</a></li>
<li class="chapter" data-level="1.10.6" data-path="general-overview.html"><a href="general-overview.html#lab-6-mini-project-4-raz-et-al.-2006"><i class="fa fa-check"></i><b>1.10.6</b> Lab 6: Mini Project 4 Raz et al. (2006)</a></li>
<li class="chapter" data-level="1.10.7" data-path="general-overview.html"><a href="general-overview.html#lab-7-paper-project-2-yin-1969"><i class="fa fa-check"></i><b>1.10.7</b> Lab 7 : Paper Project 2 Yin (1969)</a></li>
<li class="chapter" data-level="1.10.8" data-path="general-overview.html"><a href="general-overview.html#lab-8-paper-project-2-continued"><i class="fa fa-check"></i><b>1.10.8</b> Lab 8: Paper project 2 continued</a></li>
<li class="chapter" data-level="1.10.9" data-path="general-overview.html"><a href="general-overview.html#lab-9-brainstorming-for-final-project"><i class="fa fa-check"></i><b>1.10.9</b> Lab 9: Brainstorming for Final project</a></li>
<li class="chapter" data-level="1.10.10" data-path="general-overview.html"><a href="general-overview.html#lab-10-individual-presentations"><i class="fa fa-check"></i><b>1.10.10</b> Lab 10: Individual Presentations</a></li>
<li class="chapter" data-level="1.10.11" data-path="general-overview.html"><a href="general-overview.html#lab-11-13-group-work-on-final-project"><i class="fa fa-check"></i><b>1.10.11</b> Lab 11-13: Group work on Final Project</a></li>
<li class="chapter" data-level="1.10.12" data-path="general-overview.html"><a href="general-overview.html#lab-14-final-group-presentations"><i class="fa fa-check"></i><b>1.10.12</b> Lab 14: Final group presentations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="qalmri.html"><a href="qalmri.html"><i class="fa fa-check"></i><b>2</b> QALMRI</a><ul>
<li class="chapter" data-level="2.1" data-path="qalmri.html"><a href="qalmri.html#the-qalmri-method"><i class="fa fa-check"></i><b>2.1</b> The QALMRI Method</a><ul>
<li class="chapter" data-level="2.1.1" data-path="qalmri.html"><a href="qalmri.html#q-stands-for-question"><i class="fa fa-check"></i><b>2.1.1</b> Q stands for Question</a></li>
<li class="chapter" data-level="2.1.2" data-path="qalmri.html"><a href="qalmri.html#a-stands-for-alternatives"><i class="fa fa-check"></i><b>2.1.2</b> A stands for Alternatives</a></li>
<li class="chapter" data-level="2.1.3" data-path="qalmri.html"><a href="qalmri.html#l-stands-for-logic"><i class="fa fa-check"></i><b>2.1.3</b> L stands for Logic</a></li>
<li class="chapter" data-level="2.1.4" data-path="qalmri.html"><a href="qalmri.html#m-stands-for-method"><i class="fa fa-check"></i><b>2.1.4</b> M stands for Method</a></li>
<li class="chapter" data-level="2.1.5" data-path="qalmri.html"><a href="qalmri.html#r-stands-for-results"><i class="fa fa-check"></i><b>2.1.5</b> R stands for Results</a></li>
<li class="chapter" data-level="2.1.6" data-path="qalmri.html"><a href="qalmri.html#i-stands-for-inferences"><i class="fa fa-check"></i><b>2.1.6</b> I stands for Inferences</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="qalmri.html"><a href="qalmri.html#writing-a-qalmri"><i class="fa fa-check"></i><b>2.2</b> Writing a QALMRI</a></li>
<li class="chapter" data-level="2.3" data-path="qalmri.html"><a href="qalmri.html#example-qalmri"><i class="fa fa-check"></i><b>2.3</b> Example QALMRI</a><ul>
<li class="chapter" data-level="2.3.1" data-path="qalmri.html"><a href="qalmri.html#what-was-the-broad-and-specific-question"><i class="fa fa-check"></i><b>2.3.1</b> What was the broad and specific question?</a></li>
<li class="chapter" data-level="2.3.2" data-path="qalmri.html"><a href="qalmri.html#what-are-the-alternatives"><i class="fa fa-check"></i><b>2.3.2</b> What are the alternatives?</a></li>
<li class="chapter" data-level="2.3.3" data-path="qalmri.html"><a href="qalmri.html#what-is-the-logic"><i class="fa fa-check"></i><b>2.3.3</b> What is the logic?</a></li>
<li class="chapter" data-level="2.3.4" data-path="qalmri.html"><a href="qalmri.html#what-is-the-method"><i class="fa fa-check"></i><b>2.3.4</b> What is the Method?</a></li>
<li class="chapter" data-level="2.3.5" data-path="qalmri.html"><a href="qalmri.html#results"><i class="fa fa-check"></i><b>2.3.5</b> Results</a></li>
<li class="chapter" data-level="2.3.6" data-path="qalmri.html"><a href="qalmri.html#inference"><i class="fa fa-check"></i><b>2.3.6</b> Inference</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="qalmri.html"><a href="qalmri.html#finding-the-qalmri-sections-in-a-journal-article"><i class="fa fa-check"></i><b>2.4</b> Finding the QALMRI sections in a journal article</a><ul>
<li class="chapter" data-level="2.4.1" data-path="qalmri.html"><a href="qalmri.html#finding-the-big-question"><i class="fa fa-check"></i><b>2.4.1</b> Finding the Big Question</a></li>
<li class="chapter" data-level="2.4.2" data-path="qalmri.html"><a href="qalmri.html#finding-the-specific-question"><i class="fa fa-check"></i><b>2.4.2</b> Finding the Specific question</a></li>
<li class="chapter" data-level="2.4.3" data-path="qalmri.html"><a href="qalmri.html#alternatives"><i class="fa fa-check"></i><b>2.4.3</b> Alternatives</a></li>
<li class="chapter" data-level="2.4.4" data-path="qalmri.html"><a href="qalmri.html#logic"><i class="fa fa-check"></i><b>2.4.4</b> Logic</a></li>
<li class="chapter" data-level="2.4.5" data-path="qalmri.html"><a href="qalmri.html#methods"><i class="fa fa-check"></i><b>2.4.5</b> Methods</a></li>
<li class="chapter" data-level="2.4.6" data-path="qalmri.html"><a href="qalmri.html#results-1"><i class="fa fa-check"></i><b>2.4.6</b> Results</a></li>
<li class="chapter" data-level="2.4.7" data-path="qalmri.html"><a href="qalmri.html#inference-1"><i class="fa fa-check"></i><b>2.4.7</b> Inference</a></li>
<li class="chapter" data-level="2.4.8" data-path="qalmri.html"><a href="qalmri.html#reading-between-the-lines"><i class="fa fa-check"></i><b>2.4.8</b> Reading between the lines</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="qalmri.html"><a href="qalmri.html#the-hardest-section-of-the-qalrmi-alternatives"><i class="fa fa-check"></i><b>2.5</b> The Hardest Section of the QALRMI: Alternatives</a><ul>
<li class="chapter" data-level="2.5.1" data-path="qalmri.html"><a href="qalmri.html#empirical-vs.theoretical-hypotheses"><i class="fa fa-check"></i><b>2.5.1</b> Empirical vs. Theoretical Hypotheses</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="major-project-one-2-labs.html"><a href="major-project-one-2-labs.html"><i class="fa fa-check"></i><b>3</b> Major Project ONE (2 labs)</a><ul>
<li class="chapter" data-level="3.1" data-path="major-project-one-2-labs.html"><a href="major-project-one-2-labs.html#overview"><i class="fa fa-check"></i><b>3.1</b> Overview</a></li>
<li class="chapter" data-level="3.2" data-path="major-project-one-2-labs.html"><a href="major-project-one-2-labs.html#things-you-will-learn"><i class="fa fa-check"></i><b>3.2</b> Things you will learn</a></li>
<li class="chapter" data-level="3.3" data-path="major-project-one-2-labs.html"><a href="major-project-one-2-labs.html#background-readings"><i class="fa fa-check"></i><b>3.3</b> Background readings</a></li>
<li class="chapter" data-level="3.4" data-path="major-project-one-2-labs.html"><a href="major-project-one-2-labs.html#grade"><i class="fa fa-check"></i><b>3.4</b> Grade</a></li>
<li class="chapter" data-level="3.5" data-path="major-project-one-2-labs.html"><a href="major-project-one-2-labs.html#writing-the-paper"><i class="fa fa-check"></i><b>3.5</b> Writing the paper</a><ul>
<li class="chapter" data-level="3.5.1" data-path="major-project-one-2-labs.html"><a href="major-project-one-2-labs.html#apa-formatting-title-and-abstract"><i class="fa fa-check"></i><b>3.5.1</b> APA formatting, Title and Abstract</a></li>
<li class="chapter" data-level="3.5.2" data-path="major-project-one-2-labs.html"><a href="major-project-one-2-labs.html#introduction-around-2-double-spaced-pages"><i class="fa fa-check"></i><b>3.5.2</b> Introduction (around 2 double-spaced pages)</a></li>
<li class="chapter" data-level="3.5.3" data-path="major-project-one-2-labs.html"><a href="major-project-one-2-labs.html#methods-about-1-page"><i class="fa fa-check"></i><b>3.5.3</b> Methods (about 1 page)</a></li>
<li class="chapter" data-level="3.5.4" data-path="major-project-one-2-labs.html"><a href="major-project-one-2-labs.html#results-2"><i class="fa fa-check"></i><b>3.5.4</b> Results</a></li>
<li class="chapter" data-level="3.5.5" data-path="major-project-one-2-labs.html"><a href="major-project-one-2-labs.html#discussion"><i class="fa fa-check"></i><b>3.5.5</b> Discussion</a></li>
<li class="chapter" data-level="3.5.6" data-path="major-project-one-2-labs.html"><a href="major-project-one-2-labs.html#references-and-figures-or-tables"><i class="fa fa-check"></i><b>3.5.6</b> References and Figures or Tables</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="major-project-one-2-labs.html"><a href="major-project-one-2-labs.html#lab-1-data-analysis-tips"><i class="fa fa-check"></i><b>3.6</b> Data-analysis tips</a><ul>
<li class="chapter" data-level="3.6.1" data-path="major-project-one-2-labs.html"><a href="major-project-one-2-labs.html#the-t-test"><i class="fa fa-check"></i><b>3.6.1</b> The t-test</a></li>
<li class="chapter" data-level="3.6.2" data-path="major-project-one-2-labs.html"><a href="major-project-one-2-labs.html#one-more-time"><i class="fa fa-check"></i><b>3.6.2</b> One more time</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="major-project-one-2-labs.html"><a href="major-project-one-2-labs.html#writing-up-the-results-of-a-t-test"><i class="fa fa-check"></i><b>3.7</b> Writing up the results of a t-test</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="miniproject-one-memory.html"><a href="miniproject-one-memory.html"><i class="fa fa-check"></i><b>4</b> MiniProject ONE (MEMORY)</a><ul>
<li class="chapter" data-level="4.1" data-path="miniproject-one-memory.html"><a href="miniproject-one-memory.html#whats-in-store"><i class="fa fa-check"></i><b>4.1</b> What’s in store</a></li>
<li class="chapter" data-level="4.2" data-path="miniproject-one-memory.html"><a href="miniproject-one-memory.html#lab-4-data-analysis-tips"><i class="fa fa-check"></i><b>4.2</b> Data-analysis tips</a><ul>
<li class="chapter" data-level="4.2.1" data-path="miniproject-one-memory.html"><a href="miniproject-one-memory.html#simulating-the-data"><i class="fa fa-check"></i><b>4.2.1</b> Simulating the data</a></li>
<li class="chapter" data-level="4.2.2" data-path="miniproject-one-memory.html"><a href="miniproject-one-memory.html#looking-at-the-means"><i class="fa fa-check"></i><b>4.2.2</b> Looking at the means</a></li>
<li class="chapter" data-level="4.2.3" data-path="miniproject-one-memory.html"><a href="miniproject-one-memory.html#plotting-the-data"><i class="fa fa-check"></i><b>4.2.3</b> Plotting the data</a></li>
<li class="chapter" data-level="4.2.4" data-path="miniproject-one-memory.html"><a href="miniproject-one-memory.html#conducting-the-anova"><i class="fa fa-check"></i><b>4.2.4</b> Conducting the ANOVA</a></li>
<li class="chapter" data-level="4.2.5" data-path="miniproject-one-memory.html"><a href="miniproject-one-memory.html#comparisons-between-conditions"><i class="fa fa-check"></i><b>4.2.5</b> Comparisons between conditions</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="miniproject-one-memory.html"><a href="miniproject-one-memory.html#writing-it-all-up"><i class="fa fa-check"></i><b>4.3</b> Writing it all up</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="miniproject-two-task-switching.html"><a href="miniproject-two-task-switching.html"><i class="fa fa-check"></i><b>5</b> MiniProject TWO (Task-switching)</a><ul>
<li class="chapter" data-level="5.1" data-path="miniproject-two-task-switching.html"><a href="miniproject-two-task-switching.html#whats-in-store-1"><i class="fa fa-check"></i><b>5.1</b> What’s in store</a></li>
<li class="chapter" data-level="5.2" data-path="miniproject-two-task-switching.html"><a href="miniproject-two-task-switching.html#critical-concepts"><i class="fa fa-check"></i><b>5.2</b> Critical Concepts</a><ul>
<li class="chapter" data-level="5.2.1" data-path="miniproject-two-task-switching.html"><a href="miniproject-two-task-switching.html#multiple-dependent-and-independent-variables"><i class="fa fa-check"></i><b>5.2.1</b> Multiple Dependent and Independent Variables</a></li>
<li class="chapter" data-level="5.2.2" data-path="miniproject-two-task-switching.html"><a href="miniproject-two-task-switching.html#main-effects-and-interactions"><i class="fa fa-check"></i><b>5.2.2</b> Main effects and interactions</a></li>
<li class="chapter" data-level="5.2.3" data-path="miniproject-two-task-switching.html"><a href="miniproject-two-task-switching.html#manipulating-an-effect"><i class="fa fa-check"></i><b>5.2.3</b> Manipulating an Effect</a></li>
<li class="chapter" data-level="5.2.4" data-path="miniproject-two-task-switching.html"><a href="miniproject-two-task-switching.html#reducing-a-two-factor-design-to-a-single-factor-design-using-difference-scores"><i class="fa fa-check"></i><b>5.2.4</b> Reducing a two-factor design to a single-factor design using difference scores</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="miniproject-two-task-switching.html"><a href="miniproject-two-task-switching.html#data-analysis-tips"><i class="fa fa-check"></i><b>5.3</b> Data-analysis tips</a><ul>
<li class="chapter" data-level="5.3.1" data-path="miniproject-two-task-switching.html"><a href="miniproject-two-task-switching.html#simulating-the-data-1"><i class="fa fa-check"></i><b>5.3.1</b> Simulating the data</a></li>
<li class="chapter" data-level="5.3.2" data-path="miniproject-two-task-switching.html"><a href="miniproject-two-task-switching.html#plotting-the-data-1"><i class="fa fa-check"></i><b>5.3.2</b> Plotting the data</a></li>
<li class="chapter" data-level="5.3.3" data-path="miniproject-two-task-switching.html"><a href="miniproject-two-task-switching.html#running-the-anova"><i class="fa fa-check"></i><b>5.3.3</b> Running the ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="miniproject-two-task-switching.html"><a href="miniproject-two-task-switching.html#writing-up-the-results"><i class="fa fa-check"></i><b>5.4</b> Writing up the results</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="miniproject-three-stroop.html"><a href="miniproject-three-stroop.html"><i class="fa fa-check"></i><b>6</b> MiniProject THREE (Stroop)</a><ul>
<li class="chapter" data-level="6.1" data-path="miniproject-three-stroop.html"><a href="miniproject-three-stroop.html#whats-in-store-2"><i class="fa fa-check"></i><b>6.1</b> What’s in store</a></li>
<li class="chapter" data-level="6.2" data-path="miniproject-three-stroop.html"><a href="miniproject-three-stroop.html#some-background-on-the-stroop-effect"><i class="fa fa-check"></i><b>6.2</b> Some background on the Stroop effect</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="major-project-two-2-labs.html"><a href="major-project-two-2-labs.html"><i class="fa fa-check"></i><b>7</b> Major Project TWO (2 labs)</a><ul>
<li class="chapter" data-level="7.1" data-path="major-project-two-2-labs.html"><a href="major-project-two-2-labs.html#overview-1"><i class="fa fa-check"></i><b>7.1</b> Overview</a></li>
<li class="chapter" data-level="7.2" data-path="major-project-two-2-labs.html"><a href="major-project-two-2-labs.html#things-you-will-learn-1"><i class="fa fa-check"></i><b>7.2</b> Things you will learn:</a></li>
<li class="chapter" data-level="7.3" data-path="major-project-two-2-labs.html"><a href="major-project-two-2-labs.html#background-readings-1"><i class="fa fa-check"></i><b>7.3</b> Background readings:</a></li>
<li class="chapter" data-level="7.4" data-path="major-project-two-2-labs.html"><a href="major-project-two-2-labs.html#grade-1"><i class="fa fa-check"></i><b>7.4</b> Grade</a></li>
<li class="chapter" data-level="7.5" data-path="major-project-two-2-labs.html"><a href="major-project-two-2-labs.html#writing-the-paper-1"><i class="fa fa-check"></i><b>7.5</b> Writing the paper</a><ul>
<li class="chapter" data-level="7.5.1" data-path="major-project-two-2-labs.html"><a href="major-project-two-2-labs.html#apa-formatting-title-and-abstract-1"><i class="fa fa-check"></i><b>7.5.1</b> APA formatting, Title and Abstract</a></li>
<li class="chapter" data-level="7.5.2" data-path="major-project-two-2-labs.html"><a href="major-project-two-2-labs.html#introduction-around-2-double-spaced-pages-1"><i class="fa fa-check"></i><b>7.5.2</b> Introduction (around 2 double-spaced pages)</a></li>
<li class="chapter" data-level="7.5.3" data-path="major-project-two-2-labs.html"><a href="major-project-two-2-labs.html#methods-about-1-page-1"><i class="fa fa-check"></i><b>7.5.3</b> Methods (about 1 page)</a></li>
<li class="chapter" data-level="7.5.4" data-path="major-project-two-2-labs.html"><a href="major-project-two-2-labs.html#results-3"><i class="fa fa-check"></i><b>7.5.4</b> Results</a></li>
<li class="chapter" data-level="7.5.5" data-path="major-project-two-2-labs.html"><a href="major-project-two-2-labs.html#discussion-1"><i class="fa fa-check"></i><b>7.5.5</b> Discussion</a></li>
<li class="chapter" data-level="7.5.6" data-path="major-project-two-2-labs.html"><a href="major-project-two-2-labs.html#references-and-figures-or-tables-1"><i class="fa fa-check"></i><b>7.5.6</b> References and Figures or Tables</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="final-project.html"><a href="final-project.html"><i class="fa fa-check"></i><b>8</b> Final Project</a><ul>
<li class="chapter" data-level="8.1" data-path="final-project.html"><a href="final-project.html#overview-2"><i class="fa fa-check"></i><b>8.1</b> Overview</a></li>
<li class="chapter" data-level="8.2" data-path="final-project.html"><a href="final-project.html#requirements"><i class="fa fa-check"></i><b>8.2</b> Requirements</a></li>
<li class="chapter" data-level="8.3" data-path="final-project.html"><a href="final-project.html#minute-individual-presentation-5-of-total-grade"><i class="fa fa-check"></i><b>8.3</b> 2-3 minute individual presentation (5% of total grade)</a></li>
<li class="chapter" data-level="8.4" data-path="final-project.html"><a href="final-project.html#apa-style-research-report-15-of-total-grade"><i class="fa fa-check"></i><b>8.4</b> APA style research report (15% of total grade)</a></li>
<li class="chapter" data-level="8.5" data-path="final-project.html"><a href="final-project.html#minute-group-presentation-5-of-total-grade"><i class="fa fa-check"></i><b>8.5</b> 10 minute group presentation (5% of total grade)</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="how-to-write-a-research-report.html"><a href="how-to-write-a-research-report.html"><i class="fa fa-check"></i><b>9</b> How to write a research report</a><ul>
<li class="chapter" data-level="9.1" data-path="how-to-write-a-research-report.html"><a href="how-to-write-a-research-report.html#introduction"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="how-to-write-a-research-report.html"><a href="how-to-write-a-research-report.html#methods-1"><i class="fa fa-check"></i><b>9.2</b> Methods</a></li>
<li class="chapter" data-level="9.3" data-path="how-to-write-a-research-report.html"><a href="how-to-write-a-research-report.html#results-4"><i class="fa fa-check"></i><b>9.3</b> Results</a></li>
<li class="chapter" data-level="9.4" data-path="how-to-write-a-research-report.html"><a href="how-to-write-a-research-report.html#discussion-of-results"><i class="fa fa-check"></i><b>9.4</b> Discussion of results</a></li>
<li class="chapter" data-level="9.5" data-path="how-to-write-a-research-report.html"><a href="how-to-write-a-research-report.html#conclusions-and-recommendations"><i class="fa fa-check"></i><b>9.5</b> Conclusions and recommendations</a></li>
<li class="chapter" data-level="9.6" data-path="how-to-write-a-research-report.html"><a href="how-to-write-a-research-report.html#apa-style"><i class="fa fa-check"></i><b>9.6</b> APA style</a></li>
<li class="chapter" data-level="9.7" data-path="how-to-write-a-research-report.html"><a href="how-to-write-a-research-report.html#apa-style-formatting"><i class="fa fa-check"></i><b>9.7</b> APA style formatting</a></li>
<li class="chapter" data-level="9.8" data-path="how-to-write-a-research-report.html"><a href="how-to-write-a-research-report.html#sample-apa-report"><i class="fa fa-check"></i><b>9.8</b> Sample APA report</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>10</b> References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Research Methods: Lab Manual</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<img src="ResearchMethods.png" id="coverpic" width="350" style="display: block; margin: auto;" />
<div id="miniproject-two-task-switching" class="section level1">
<h1><span class="header-section-number">Chapter 5</span> MiniProject TWO (Task-switching)</h1>
<script>
$("#coverpic").hide();
</script>
<p>In the second mini-project, you will read, summarize and discuss the paper by <span class="citation">Stoet et al. (<a href="#ref-stoet_are_2013">2013</a>)</span>. Then, you will attempt to replicate their results in the lab, by conducting an experiment and analyzing the data.</p>
<div id="whats-in-store-1" class="section level2">
<h2><span class="header-section-number">5.1</span> What’s in store</h2>
<ol style="list-style-type: decimal">
<li><p>Students read paper and write QALMRI (15-20)</p></li>
<li><p>Group discussion about paper (15-20)</p></li>
<li><p>Students download the task-switching program available from the website and individually complete the task. Individual students then enter their data in the master spreadsheet</p></li>
<li><p>Discussion of how to analyze the data. Major analysis goals are:</p>
<ol style="list-style-type: lower-alpha">
<li><p>Was there a mixing cost? Compare pure lists to mixed lists</p></li>
<li><p>Was there a switching cost? Compare switch vs. repeat trials in pure lists</p></li>
<li><p>Did these effects depend on gender? Did the women have a smaller mixing cost than the men? Did the women have a smaller switching cost than the men?</p></li>
</ol></li>
<li><p>Students break into groups to analyze the data.</p></li>
</ol>
</div>
<div id="critical-concepts" class="section level2">
<h2><span class="header-section-number">5.2</span> Critical Concepts</h2>
<div id="multiple-dependent-and-independent-variables" class="section level3">
<h3><span class="header-section-number">5.2.1</span> Multiple Dependent and Independent Variables</h3>
<p>In lab 5 we begin looking at more complex designs that involve multiple dependent or and independent variables. For example, we can look at the dependent variable of reaction time or error rate, which are our two difference measured variables. There are also three independent variables, including gender (male vs female), block (pure list vs. mixed list), and trial sequence (repeat trial vs. switch trial).</p>
</div>
<div id="main-effects-and-interactions" class="section level3">
<h3><span class="header-section-number">5.2.2</span> Main effects and interactions</h3>
<p>Throughout this course we will be talking a lot about main effects and interactions. Feel free to jump ahead in the textbook and learn more about them.</p>
<p>Main effects refer to the influence of single independent variables. And, each independent variable always has one main effect. So, we could look at the main effect of gender, block, or trial sequence. The main effect is like conducting a one-way ANOVA on the variable of interest, collapsing over the other variables. For example, a main effect of trial sequence usually shows slower mean reaction times in the switch condition compared to the repeat condition. This is called the task-switching cost, or also the task-switching effect.</p>
<p>Interactions occur when the effect of one independent variable depends on the levels of another independent variable. For example, if women actually multi-task better than men, then we should expect an interaction between gender and task-switching. Specifically, women should be better at task-switching than men. This would mean that women should have smaller task-switching costs (meaning they are unaffected by switching) compared to men (who should have bigger task-switching costs if they are more affected by switching).</p>
<p>If women have smaller task switching costs than men, then the effect of task-switching independent variable (repeat vs. switch) will depend on the level of the gender variable (women vs. men), which is the definition of an interaction.</p>
</div>
<div id="manipulating-an-effect" class="section level3">
<h3><span class="header-section-number">5.2.3</span> Manipulating an Effect</h3>
<p>Things get complicated when we add more dependent and independent variables, and it can be easy to lose track of what is going on in an experiment.</p>
<p>Many experiments are conducted for the purpose of better understanding some phenomena. For example, researchers observe phenomena like the task-switching effect, they create theories to explain the phenomena, then they test their theories by running more experiments.</p>
<p>A primary question is often to identify factors that manipulate, influence, or somehow change the phenomena of interest. We know that switching between tasks can hurt performance, and we measure this cost by calculating a switch cost, which is the difference in performance between switching conditions and repeating conditions. What kinds of factors would make this cost ? Perhaps extended practice, time of day, gender, personality, motivation, drug interventions, details of the task, and many other factors could make the normal cost get smaller. Many of these factors might also make the effect get larger. And, knowledge of what makes switching costs smaller or larger can be used to test theories, which need to explain how and why those factors cause switching costs to change.</p>
<p>The Stoet et al. (2013) took this approach to determine if switch costs are smaller for men than women. Notice we have been talking about switch costs, which is the phenonemon and effect of interest. We have not been talking too much about the dependent variable of reaction times that we use to compute the switch costs. Remember that switch costs are computed as RT switch - RT repeat.</p>
</div>
<div id="reducing-a-two-factor-design-to-a-single-factor-design-using-difference-scores" class="section level3">
<h3><span class="header-section-number">5.2.4</span> Reducing a two-factor design to a single-factor design using difference scores</h3>
<p>We can use the term switch cost as a convenient term to describe the effect of the switching variable on reaction times. We can also think of the switch cost as the dependent variable of interest, rather than the base reaction time scores. Thinking of the switch cost this way can change how you conceptualize the design.</p>
<p>For example, how many independent variables are in a design testing whether women have smaller switch costs than men? The answer could be two or one, depending on how you think of the design.</p>
<p>If we go with two, then the design involves the independent variables gender (women vs. men) and trial sequence (switch vs. repeat), and the dependent variable of reaction time. This design would have two main effects (effect of gender, and effect of switching), and one interaction (gender x switching). We would be mainly interested in the interaction. For example, women may have a smaller difference in mean reaction time between the switch and repeat conditions than men.</p>
<p>We can reduce the design to a simple single-factor design. To do so, we create a new dependent variable called switch costs. For example, for each subject we compute the mean reaction in the switch and repeat condition. Then we calculate the switch costs (difference between switch and repeat) for each subject. Now, each subject has one switch cost, rather than two reaction times. Now, the design would have gender as the single independent variable, and switch costs as the dependent variable. To determine whether women have smaller costs than men would you could run a t-test comparing the switch-costs between conditions.</p>
<p>In addition to this material below, you can also look at the examples of conducting <a href="https://crumplab.github.io/statisticsLab/lab-11-mixed-factorial-anova.html">factorial ANOVAs in software using the lab manual from PSYC 3400 Introductory Statistics</a>, and refresh your understanding of factorial ANOVAs by <a href="https://crumplab.github.io/statistics/factorial-anova.html">reading the Factorial ANOVA chapter from the PSYC 3400 textbook</a>.</p>
</div>
</div>
<div id="data-analysis-tips" class="section level2">
<h2><span class="header-section-number">5.3</span> Data-analysis tips</h2>
<p>To give you an idea about the analyses you will be performing, we will again create simulated data to mimic aspects of the experiment, and then go through the steps of performing the analysis.</p>
<p>We will simulate data for the switching cost. Specifically, we will imagine that women have a smaller switching cost than men. The code below generates sample data for 10 women and 10 men, who each have mean reactions in the repeat and switch conditions. For women, the mean reaction times were 580 ms for repeat and 600 ms for switch sequences, for a total expected switch cost of 20 ms. For men, the mean reaction times were 580 ms for repeat and 650 ms for switch sequences, for a total expected switch cost of 70 ms.</p>
<div id="simulating-the-data-1" class="section level3">
<h3><span class="header-section-number">5.3.1</span> Simulating the data</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">women_switch &lt;-<span class="kw">round</span>(<span class="kw">rnorm</span>(<span class="dv">10</span>,<span class="dv">600</span>,<span class="dv">20</span>))
women_repeat &lt;-<span class="kw">round</span>(<span class="kw">rnorm</span>(<span class="dv">10</span>,<span class="dv">580</span>,<span class="dv">20</span>))
men_switch &lt;-<span class="kw">round</span>(<span class="kw">rnorm</span>(<span class="dv">10</span>,<span class="dv">650</span>,<span class="dv">20</span>))
men_repeat &lt;-<span class="kw">round</span>(<span class="kw">rnorm</span>(<span class="dv">10</span>,<span class="dv">580</span>,<span class="dv">20</span>))
all_data&lt;-<span class="kw">data.frame</span>(<span class="dt">Subject=</span><span class="kw">c</span>(<span class="kw">rep</span>(<span class="kw">seq</span>(<span class="dv">1</span>,<span class="dv">10</span>,<span class="dv">1</span>),<span class="dv">2</span>),
                               <span class="kw">rep</span>(<span class="kw">seq</span>(<span class="dv">11</span>,<span class="dv">20</span>,<span class="dv">1</span>),<span class="dv">2</span>)),
                     <span class="dt">Gender=</span><span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;Female&quot;</span>,<span class="st">&quot;Male&quot;</span>),<span class="dt">each=</span><span class="dv">20</span>),
                     <span class="dt">Sequence=</span><span class="kw">rep</span>(<span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;switch&quot;</span>,<span class="st">&quot;repeat&quot;</span>),<span class="dt">each=</span><span class="dv">10</span>),<span class="dv">2</span>),
                     <span class="dt">RT=</span><span class="kw">c</span>(women_switch,women_repeat,
                          men_switch,men_repeat))

knitr::<span class="kw">kable</span>(all_data)</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">Subject</th>
<th align="left">Gender</th>
<th align="left">Sequence</th>
<th align="right">RT</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">Female</td>
<td align="left">switch</td>
<td align="right">587</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">Female</td>
<td align="left">switch</td>
<td align="right">582</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="left">Female</td>
<td align="left">switch</td>
<td align="right">574</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="left">Female</td>
<td align="left">switch</td>
<td align="right">601</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="left">Female</td>
<td align="left">switch</td>
<td align="right">626</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="left">Female</td>
<td align="left">switch</td>
<td align="right">576</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="left">Female</td>
<td align="left">switch</td>
<td align="right">587</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="left">Female</td>
<td align="left">switch</td>
<td align="right">592</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="left">Female</td>
<td align="left">switch</td>
<td align="right">596</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="left">Female</td>
<td align="left">switch</td>
<td align="right">577</td>
</tr>
<tr class="odd">
<td align="right">1</td>
<td align="left">Female</td>
<td align="left">repeat</td>
<td align="right">596</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">Female</td>
<td align="left">repeat</td>
<td align="right">574</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="left">Female</td>
<td align="left">repeat</td>
<td align="right">531</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="left">Female</td>
<td align="left">repeat</td>
<td align="right">596</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="left">Female</td>
<td align="left">repeat</td>
<td align="right">542</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="left">Female</td>
<td align="left">repeat</td>
<td align="right">604</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="left">Female</td>
<td align="left">repeat</td>
<td align="right">569</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="left">Female</td>
<td align="left">repeat</td>
<td align="right">565</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="left">Female</td>
<td align="left">repeat</td>
<td align="right">602</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="left">Female</td>
<td align="left">repeat</td>
<td align="right">556</td>
</tr>
<tr class="odd">
<td align="right">11</td>
<td align="left">Male</td>
<td align="left">switch</td>
<td align="right">639</td>
</tr>
<tr class="even">
<td align="right">12</td>
<td align="left">Male</td>
<td align="left">switch</td>
<td align="right">689</td>
</tr>
<tr class="odd">
<td align="right">13</td>
<td align="left">Male</td>
<td align="left">switch</td>
<td align="right">635</td>
</tr>
<tr class="even">
<td align="right">14</td>
<td align="left">Male</td>
<td align="left">switch</td>
<td align="right">655</td>
</tr>
<tr class="odd">
<td align="right">15</td>
<td align="left">Male</td>
<td align="left">switch</td>
<td align="right">681</td>
</tr>
<tr class="even">
<td align="right">16</td>
<td align="left">Male</td>
<td align="left">switch</td>
<td align="right">654</td>
</tr>
<tr class="odd">
<td align="right">17</td>
<td align="left">Male</td>
<td align="left">switch</td>
<td align="right">674</td>
</tr>
<tr class="even">
<td align="right">18</td>
<td align="left">Male</td>
<td align="left">switch</td>
<td align="right">658</td>
</tr>
<tr class="odd">
<td align="right">19</td>
<td align="left">Male</td>
<td align="left">switch</td>
<td align="right">630</td>
</tr>
<tr class="even">
<td align="right">20</td>
<td align="left">Male</td>
<td align="left">switch</td>
<td align="right">645</td>
</tr>
<tr class="odd">
<td align="right">11</td>
<td align="left">Male</td>
<td align="left">repeat</td>
<td align="right">553</td>
</tr>
<tr class="even">
<td align="right">12</td>
<td align="left">Male</td>
<td align="left">repeat</td>
<td align="right">564</td>
</tr>
<tr class="odd">
<td align="right">13</td>
<td align="left">Male</td>
<td align="left">repeat</td>
<td align="right">573</td>
</tr>
<tr class="even">
<td align="right">14</td>
<td align="left">Male</td>
<td align="left">repeat</td>
<td align="right">567</td>
</tr>
<tr class="odd">
<td align="right">15</td>
<td align="left">Male</td>
<td align="left">repeat</td>
<td align="right">561</td>
</tr>
<tr class="even">
<td align="right">16</td>
<td align="left">Male</td>
<td align="left">repeat</td>
<td align="right">580</td>
</tr>
<tr class="odd">
<td align="right">17</td>
<td align="left">Male</td>
<td align="left">repeat</td>
<td align="right">581</td>
</tr>
<tr class="even">
<td align="right">18</td>
<td align="left">Male</td>
<td align="left">repeat</td>
<td align="right">563</td>
</tr>
<tr class="odd">
<td align="right">19</td>
<td align="left">Male</td>
<td align="left">repeat</td>
<td align="right">619</td>
</tr>
<tr class="even">
<td align="right">20</td>
<td align="left">Male</td>
<td align="left">repeat</td>
<td align="right">544</td>
</tr>
</tbody>
</table>
</div>
<div id="plotting-the-data-1" class="section level3">
<h3><span class="header-section-number">5.3.2</span> Plotting the data</h3>
<p>We can plot the data at least two ways. See the bar and line graphs below. Note that the x-axis changes between graphs.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)
<span class="kw">library</span>(plyr)
sde&lt;-function(x){<span class="kw">sd</span>(x)/<span class="kw">length</span>(x)}
plot_means&lt;-<span class="kw">ddply</span>(all_data,.(Gender,Sequence),summarise,
                       <span class="dt">MeanRT=</span><span class="kw">mean</span>(RT),
                       <span class="dt">SE=</span><span class="kw">sde</span>(RT))

limits &lt;-<span class="st"> </span><span class="kw">aes</span>(<span class="dt">ymax =</span> MeanRT +<span class="st"> </span>SE, <span class="dt">ymin =</span> MeanRT -<span class="st"> </span>SE)

<span class="kw">ggplot</span>(plot_means,<span class="kw">aes</span>(<span class="dt">x=</span>Gender, <span class="dt">y=</span>MeanRT, <span class="dt">group=</span>Sequence,<span class="dt">fill=</span>Sequence))+
<span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">position=</span><span class="st">&quot;dodge&quot;</span>,<span class="dt">stat=</span><span class="st">&quot;identity&quot;</span>)+
<span class="st">  </span><span class="kw">geom_errorbar</span>(limits, <span class="dt">width=</span>.<span class="dv">3</span>,<span class="dt">position=</span><span class="kw">position_dodge</span>(.<span class="dv">9</span>))+
<span class="st">  </span><span class="kw">theme_classic</span>(<span class="dt">base_size=</span><span class="dv">12</span>)+
<span class="st">  </span><span class="kw">coord_cartesian</span>(<span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">500</span>,<span class="dv">700</span>))+
<span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;Mean RT&quot;</span>)+
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Trial sequence&quot;</span>)</code></pre></div>
<p><img src="Methods_Lab_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(plot_means,<span class="kw">aes</span>(<span class="dt">x=</span>Sequence, <span class="dt">y=</span>MeanRT, <span class="dt">group=</span>Gender,<span class="dt">shape=</span>Gender))+
<span class="st">  </span><span class="kw">geom_line</span>()+
<span class="st">  </span><span class="kw">geom_point</span>()+
<span class="st">  </span><span class="kw">geom_errorbar</span>(limits, <span class="dt">width=</span>.<span class="dv">2</span>)+
<span class="st">  </span><span class="kw">theme_classic</span>(<span class="dt">base_size=</span><span class="dv">12</span>)+
<span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;Mean RT&quot;</span>)+
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Trial sequence&quot;</span>)</code></pre></div>
<p><img src="Methods_Lab_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>The graphs show that the switch costs (difference between repeat and switch trials) is smaller for women and men. Which is good, because we are simulating the data with this outcome in mind.</p>
</div>
<div id="running-the-anova" class="section level3">
<h3><span class="header-section-number">5.3.3</span> Running the ANOVA</h3>
<p>The next step is to conduct an ANOVA. This design has two factors or independent variables, gender and trial sequence. The gender variable is between-subjects, and the trial sequence variable is within subjects. So, we will run a 2 (Gender: Female vs. Male) x 2 (trial sequence: Repeat vs. Switch) mixed design ANOVA with Gender as the betwen-subjects factor, and trial sequence as the within-subjects factor.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(broom)
<span class="kw">library</span>(xtable)
all_data$Subject&lt;-<span class="kw">as.factor</span>(all_data$Subject)
aov.out&lt;-<span class="kw">aov</span>(RT~Gender*Sequence+<span class="kw">Error</span>(Subject/Sequence),all_data)
aov_summary&lt;-<span class="kw">summary</span>(aov.out)
knitr::<span class="kw">kable</span>(<span class="kw">xtable</span>(aov_summary))</code></pre></div>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">Df</th>
<th align="right">Sum Sq</th>
<th align="right">Mean Sq</th>
<th align="right">F value</th>
<th align="right">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Gender</td>
<td align="right">1</td>
<td align="right">9985.6</td>
<td align="right">9985.6000</td>
<td align="right">28.08757</td>
<td align="right">0.0000488</td>
</tr>
<tr class="even">
<td>Residuals</td>
<td align="right">18</td>
<td align="right">6399.3</td>
<td align="right">355.5167</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="odd">
<td>Sequence</td>
<td align="right">1</td>
<td align="right">25908.1</td>
<td align="right">25908.1000</td>
<td align="right">51.49976</td>
<td align="right">0.0000011</td>
</tr>
<tr class="even">
<td>Gender:Sequence</td>
<td align="right">1</td>
<td align="right">11971.6</td>
<td align="right">11971.6000</td>
<td align="right">23.79698</td>
<td align="right">0.0001209</td>
</tr>
<tr class="odd">
<td>Residuals</td>
<td align="right">18</td>
<td align="right">9055.3</td>
<td align="right">503.0722</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
</tbody>
</table>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mt&lt;-<span class="kw">model.tables</span>(aov.out,<span class="st">&quot;means&quot;</span>)
mt</code></pre></div>
<pre><code>## Tables of means
## Grand mean
##        
## 597.45 
## 
##  Gender 
## Gender
## Female   Male 
##  581.6  613.2 
## 
##  Sequence 
## Sequence
## repeat switch 
##  572.0  622.9 
## 
##  Gender:Sequence 
##         Sequence
## Gender   repeat switch
##   Female 573.5  589.8 
##   Male   570.5  656.0</code></pre>
<p>The above shows the ANOVA table and the means for the main effects and interaction. We also conduct t.test comparisons to look at the switch costs separately for men and women.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">FemaleT&lt;-<span class="kw">t.test</span>(RT~Sequence,all_data[all_data$Gender==<span class="st">&quot;Female&quot;</span>,],<span class="dt">paired=</span><span class="ot">TRUE</span>,<span class="dt">var.equal=</span><span class="ot">TRUE</span>)
MaleT&lt;-<span class="kw">t.test</span>(RT~Sequence,all_data[all_data$Gender==<span class="st">&quot;Male&quot;</span>,],<span class="dt">paired=</span><span class="ot">TRUE</span>,<span class="dt">var.equal=</span><span class="ot">TRUE</span>)
FemaleT</code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  RT by Sequence
## t = -1.6548, df = 9, p-value = 0.1323
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -38.582344   5.982344
## sample estimates:
## mean of the differences 
##                   -16.3</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">MaleT</code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  RT by Sequence
## t = -8.3757, df = 9, p-value = 1.531e-05
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -108.59235  -62.40765
## sample estimates:
## mean of the differences 
##                   -85.5</code></pre>
</div>
</div>
<div id="writing-up-the-results" class="section level2">
<h2><span class="header-section-number">5.4</span> Writing up the results</h2>
<p>The next step is to interpret the results and write them up. Here is an example write-up.</p>
<p>The mean reaction times for each subject in trial sequence condition were submitted to a 2 (Gender: Female vs. Male) x 2 (trial sequence: Repeat vs. Switch) mixed design ANOVA with Gender as the betwen-subjects factor, and trial sequence as the within-subjects factor. Mean reaction times in each condition collapsed across subjects are displayed in Figure 1.</p>
<p>The main effect of gender was significant, F(1, 18) = 28.09, MSE = 355.52, p &lt; 0. Women (582 ms) had faster mean reaction times than men (613 ms).</p>
<p>The main effect of trials sequence was significant, F(1, 18) = 51.5, MSE = 503.07, p &lt; 0. Repeat trials (572) had faster mean reaction times than switch trials (623).</p>
<p>Most important was the significant two-way interaction between gender and trial sequence, F(1, 18) = 23.8, MSE = 503.07, p &lt; 0. We interpreted the interaction further by conducting the following comparisons. Women showed a significant switch cost, t(9) = -1.65, p = 0.132, with faster mean reaction times for repeat (574) than switch (590) trials. Men also showed a significant switch cost, t(9) = -8.38, p = 0, with faster mean reaction times for repeat (570) than switch trials (656). The presence of an interaction indicates that the size of the switch cost for women was significantly smaller than the size of the switch cost for men.</p>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-stoet_are_2013">
<p>Stoet, Gijsbert, Daryl B. O’Connor, Mark Conner, and Keith R. Laws. 2013. “Are Women Better Than Men at Multi-Tasking?” <em>BMC Psychology</em> 1 (1): 18.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="miniproject-one-memory.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="miniproject-three-stroop.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/CrumpLab/statisticsLab/blob/master/05-MiniSwitch.Rmd",
"text": "Edit"
},
"download": ["Methods_Lab.pdf"],
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
